# Site Settings

title: "Interactive Web Applications with RShiny"
baseurl: /basic-Shiny-lesson
email: cyberhelp@sesync.org
description: ""
# styleurl: https://cdn.rawgit.com/sesync-ci/lesson-stylesheets/1.0.0
styleurl: https://rawgit.com/sesync-ci/lesson-stylesheets/master
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
authors:
 - Kelly Hondula
 - Ian Carroll
 
# Slide Settings

slide_sorter:
  - title
  - intro
  - files
  - env
  - io
  - layout
  - reactive
  - button
  - share
  
# Jekyll

markdown: kramdown
collections:
  - slides
exclude:
  - README.md
  - build.R
  - "*.Rproj"
  - "*.Rmd"
